Repository nextcloud/calendar-availability-vue, pull requests merged in 2023-10, with the labels that each got.

#157 chore: Bump @nextcloud/vue to v8-beta.7
  package-lock.json
  package.json
  src/CalendarAvailability.vue
Labels: 3. to review

#161 chore(release): v2.0.0-beta.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: technial debt

#165 fix: delete button and row alignment
  src/CalendarAvailability.vue
Labels: bug, 3. to review

#166 [stable1.0] fix: delete button and row alignment
  src/CalendarAvailability.vue
Labels: bug, 3. to review
