Repository nextcloud/calendar-availability-vue, pull requests merged in 2024-02, with the labels that each got.

#222 chore: update workflows from templates
  .github/workflows/lint-eslint.yml
Labels: dependencies, automated, 3. to review

#225 build: migrate to @nextcloud/vite-config
  package-lock.json
  package.json
  vite.config.js
Labels: 3. to review

#213 Update npm and node engines versions
  package.json
Labels: dependencies

#227 release: v2.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: technial debt

#231 fix: changed aria-labels on weekday list, only on ul container now
  src/CalendarAvailability.vue
Labels: bug, enhancement, 3. to review
