Repository nextcloud/calendar-availability-vue, pull requests merged in 2024-11, with the labels that each got.

#301 chore: update workflows from templates
  .github/workflows/lint-eslint.yml
  .github/workflows/npm-audit-fix.yml
Labels: dependencies, automated, 3. to review

#338 [stable1.0] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#333 Add reuse compliance
  .eslintrc.cjs
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report_form.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request_form.yml
  .github/workflows/build.yml
  .github/workflows/commits.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/release.yml
  .github/workflows/reuse.yml
  .gitignore
  .npmignore
  AUTHORS.md
  CHANGELOG.md
  LICENSES/AGPL-3.0-or-later.txt
  LICENSES/CC0-1.0.txt
  LICENSES/MIT.txt
  README.md
  REUSE.toml
  src/CalendarAvailability.vue
  src/convert.js
  src/index.js
  src/utils/logger.js
  vite.config.js
Labels: 3. to review, technial debt

#341 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review
