Repository nextcloud/calendar-availability-vue, pull requests merged in 2024-01, with the labels that each got.

#200 chore: update workflows from templates
  .github/workflows/lint-eslint.yml
Labels: dependencies, automated, 3. to review

#210 chore(github): Request GVodyanov for npm package bump reviews
  .github/dependabot.yml
Labels: 3. to review

#216 chore(vue3): remove dead styles containing deprecated ::v-deep syntax
  src/CalendarAvailability.vue
Labels: 3. to review, technial debt
