Repository nextcloud/calendar-availability-vue, pull requests merged in 2025-01, with the labels that each got.

#348 fix: time shifting when parsing slots
  src/convert.js
Labels: bug, 3. to review

#349 ci(build): install node and npm according to engines spec
  .github/workflows/build.yml
  REUSE.toml
Labels: 3. to review

#352 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review
