Repository nextcloud/calendar-availability-vue, pull requests merged in 2025-07, with the labels that each got.

#397 [stable1.0] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#399 feat!: migrate to vue 3
  package-lock.json
  package.json
  src/CalendarAvailability.vue
Labels: enhancement, 3. to review

#403 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#402 chore(release): v3.0.0-rc.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#410 [stable2.2] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#407 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review
